name: Test Scipy
on: [push]

defaults:
  run:
    shell: bash

jobs:
  test_scipy:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        python_version: ["3.9", "3.10"]
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - run: docker build --build-arg PYTHON_VERSION=${{ matrix.python_version }} -t test_build .
      - run: docker run test_build python -c "import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)"
      - run: docker run test_build python -c "from scipy.sparse import csr_matrix"
