name: Test Scipy
on: [push]

defaults:
  run:
    shell: bash

jobs:
  test_scipy:
    runs-on: windows-2019
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - run: docker build -t test_build .
      - run: docker run test_build python -c "import scipy.linalg"
