name: Test Scipy
on: [push]

defaults:
  run:
    shell: bash

jobs:
  test_scipy:
    runs-on: windows-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - run: docker build -t test_build .
